[sdk_vector]Support binary flat and binary ivf flat
dingodb/pydingo pull request #72
Opened 2024-12-25 12:56 UTC by lry22221111

2024-12-25 12:59 UTC, chuandew approved these changes
LGTM

2024-12-25 15:46 UTC, ketor requested changes

2024-12-25 15:46 UTC, ketor commented on dingodb/sdk_vector/sdk_vector_client.py
> +        elif index_type == "binary_flay":
flay -> flat

2024-12-26 09:06 UTC, ketor approved these changes

2024-12-26 09:06 UTC, merged